//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string str_status { get; set; }
        public string dat_fecha { get; set; }
        public string str_nombre { get; set; }
        public string str_direccion { get; set; }
        public string str_departamento { get; set; }
        public string int_telefono { get; set; }
    }
}
